"""sugar table

Revision ID: 1c73cd005dc1
Revises: 1b1345cca0af
Create Date: 2020-05-02 18:53:16.011361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c73cd005dc1'
down_revision = '1b1345cca0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sugar_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eat', sa.String(length=140), nullable=True),
    sa.Column('mol', sa.Float(precision=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sugar_table_timestamp'), 'sugar_table', ['timestamp'], unique=False)
    op.drop_index('ix_sugar_timestamp', table_name='sugar')
    op.drop_table('sugar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sugar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('eat', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('mol', sa.FLOAT(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sugar_timestamp', 'sugar', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_sugar_table_timestamp'), table_name='sugar_table')
    op.drop_table('sugar_table')
    # ### end Alembic commands ###
