"""sugarlevel,carb lev

Revision ID: 2edb79a4ec03
Revises: 761a84ead571
Create Date: 2020-05-12 07:13:43.805610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edb79a4ec03'
down_revision = '761a84ead571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('carbohydrates_level', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('sugarlevel', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sugarlevel')
    op.drop_column('user', 'carbohydrates_level')
    # ### end Alembic commands ###
