"""foodtable

Revision ID: 3494d3d8da83
Revises: 791befa7f5f3
Create Date: 2020-05-12 00:18:51.395903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3494d3d8da83'
down_revision = '791befa7f5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_table_timestamp', table_name='food_table')
    op.drop_table('food_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('food', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('carbohydrates', sa.FLOAT(), nullable=True),
    sa.Column('fats', sa.FLOAT(), nullable=True),
    sa.Column('protein', sa.FLOAT(), nullable=True),
    sa.Column('eating', sa.VARCHAR(length=140), nullable=True),
    sa.Column('kkal', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_table_timestamp', 'food_table', ['timestamp'], unique=False)
    # ### end Alembic commands ###
