"""no weight

Revision ID: 47ec11d70f73
Revises: 7ab84d7765fd
Create Date: 2020-05-21 16:00:53.334310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ec11d70f73'
down_revision = '7ab84d7765fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
