"""user db age, diatype

Revision ID: 5596701f7215
Revises: c1c7740d68a7
Create Date: 2020-05-11 19:01:06.645287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5596701f7215'
down_revision = 'c1c7740d68a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('diatype', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('full_name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'diatype')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
