"""time after eating

Revision ID: 56eb677e2d2a
Revises: 98536b22690e
Create Date: 2020-05-21 23:47:24.619313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eb677e2d2a'
down_revision = '98536b22690e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sugar_table', sa.Column('time_after_eating', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sugar_table', 'time_after_eating')
    # ### end Alembic commands ###
