"""new docuser

Revision ID: 5a343ad5a7a3
Revises: 7c8afec2bcd4
Create Date: 2020-02-17 00:22:27.995465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a343ad5a7a3'
down_revision = '7c8afec2bcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docuser_email'), 'docuser', ['email'], unique=True)
    op.create_index(op.f('ix_docuser_username'), 'docuser', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docuser_username'), table_name='docuser')
    op.drop_index(op.f('ix_docuser_email'), table_name='docuser')
    op.drop_table('docuser')
    # ### end Alembic commands ###
