"""food base

Revision ID: 5e0773c84c42
Revises: fd3998a682eb
Create Date: 2020-05-09 04:35:29.501171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0773c84c42'
down_revision = 'fd3998a682eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_data')
    # ### end Alembic commands ###
