"""carb in food tbl

Revision ID: 5f7eb50c9018
Revises: 2edb79a4ec03
Create Date: 2020-05-12 07:50:27.022676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7eb50c9018'
down_revision = '2edb79a4ec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_table', sa.Column('carbohydrates', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_table', 'carbohydrates')
    # ### end Alembic commands ###
