"""food db category

Revision ID: 6a2a5bf77d17
Revises: 5e0773c84c42
Create Date: 2020-05-09 04:46:12.179499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2a5bf77d17'
down_revision = '5e0773c84c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_data', sa.Column('category', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_data', 'category')
    # ### end Alembic commands ###
