"""predict

Revision ID: 75098daf9e09
Revises: 56eb677e2d2a
Create Date: 2020-05-23 04:37:26.322668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75098daf9e09'
down_revision = '56eb677e2d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sugar_table', sa.Column('predict', sa.Float(precision=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sugar_table', 'predict')
    # ### end Alembic commands ###
