"""user kkal base

Revision ID: 761a84ead571
Revises: 9f2db58407e7
Create Date: 2020-05-12 04:50:46.022053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761a84ead571'
down_revision = '9f2db58407e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('kkal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kkal')
    # ### end Alembic commands ###
