"""weight in users

Revision ID: 77685149c97e
Revises: bdc504d0b30e
Create Date: 2020-03-09 03:28:32.454226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77685149c97e'
down_revision = 'bdc504d0b30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###
