"""food db 2k+

Revision ID: 791befa7f5f3
Revises: 6a2a5bf77d17
Create Date: 2020-05-09 20:24:12.897976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791befa7f5f3'
down_revision = '6a2a5bf77d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_datatable_index', table_name='food_datatable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_food_datatable_index', 'food_datatable', ['index'], unique=False)
    # ### end Alembic commands ###
