"""sport

Revision ID: 7ab84d7765fd
Revises: 5f7eb50c9018
Create Date: 2020-05-19 23:46:52.748737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab84d7765fd'
down_revision = '5f7eb50c9018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=140), nullable=True),
    sa.Column('time', sa.Float(precision=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_timestamp'), 'sport', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_timestamp'), table_name='sport')
    op.drop_table('sport')
    # ### end Alembic commands ###
