"""doc table

Revision ID: 7c8afec2bcd4
Revises: 93e816c5e60f
Create Date: 2020-02-12 23:09:48.278747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8afec2bcd4'
down_revision = '93e816c5e60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_user_email'), 'doc_user', ['email'], unique=True)
    op.create_index(op.f('ix_doc_user_username'), 'doc_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_user_username'), table_name='doc_user')
    op.drop_index(op.f('ix_doc_user_email'), table_name='doc_user')
    op.drop_table('doc_user')
    # ### end Alembic commands ###
