"""foodTable note

Revision ID: 84f1d658a65e
Revises: 791befa7f5f3
Create Date: 2020-05-11 04:39:03.259091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f1d658a65e'
down_revision = '791befa7f5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_table_timestamp'), 'food_table', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_table_timestamp'), table_name='food_table')
    op.drop_table('food_table')
    # ### end Alembic commands ###
