"""weight

Revision ID: 98536b22690e
Revises: f9652699a9f7
Create Date: 2020-05-21 16:19:51.025182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98536b22690e'
down_revision = 'f9652699a9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###
