"""previos deleted foodtable kkal

Revision ID: 9f2db58407e7
Revises: 3494d3d8da83
Create Date: 2020-05-12 00:20:34.822975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2db58407e7'
down_revision = '3494d3d8da83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=140), nullable=True),
    sa.Column('eating', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kkal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_table_timestamp'), 'food_table', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_table_timestamp'), table_name='food_table')
    op.drop_table('food_table')
    # ### end Alembic commands ###
