"""doc in users

Revision ID: bdc504d0b30e
Revises: 7c8afec2bcd4
Create Date: 2020-03-03 12:57:02.256265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc504d0b30e'
down_revision = '7c8afec2bcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('doctor', sa.Binary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'doctor')
    # ### end Alembic commands ###
