"""p f c foodtable

Revision ID: c1c7740d68a7
Revises: 84f1d658a65e
Create Date: 2020-05-11 05:21:25.442418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c7740d68a7'
down_revision = '84f1d658a65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_table', sa.Column('carbohydrates', sa.Float(), nullable=True))
    op.add_column('food_table', sa.Column('fats', sa.Float(), nullable=True))
    op.add_column('food_table', sa.Column('protein', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_table', 'protein')
    op.drop_column('food_table', 'fats')
    op.drop_column('food_table', 'carbohydrates')
    # ### end Alembic commands ###
