"""bmi n height

Revision ID: f9652699a9f7
Revises: 47ec11d70f73
Create Date: 2020-05-21 16:05:02.886840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9652699a9f7'
down_revision = '47ec11d70f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('BMI', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', sa.INTEGER(), nullable=True))
    op.drop_column('user', 'height')
    op.drop_column('user', 'BMI')
    # ### end Alembic commands ###
